[package]
name = "criterion-parse-rs"
version = "0.1.0"
authors = ["Julia Naomi <jnboeira@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
edn-rs = "0.13.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "parse"
harness = false